CC=g++

probeam: main.cpp CalculationsWrapper.cpp DataIO.cpp Decoder.cpp InfoForEdmanDegradation.cpp StateFunctions.cpp ArgParser.cpp InitStates.cpp
	$(CC) -o ../bin/probeam main.cpp CalculationsWrapper.cpp DataIO.cpp Decoder.cpp InfoForEdmanDegradation.cpp StateFunctions.cpp ArgParser.cpp InitStates.cpp -O3 -I. 
