CC=g++

beamDec: main.cpp CalculationsWrapper.cpp DataIO.cpp Decoder.cpp InfoForEdmanDegradation.cpp StateFunctions.cpp ArgParser.cpp
	$(CC) -o BeamDec main.cpp CalculationsWrapper.cpp DataIO.cpp Decoder.cpp InfoForEdmanDegradation.cpp StateFunctions.cpp ArgParser.cpp -O3 -I. 